spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5356/mydb
    username: myuser
    password: mypassword
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
