name: test-project

on:
  push:
    branches:
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository to get access to the code
        uses: actions/checkout@v4
      - name: cache npm dependencies
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: build dependencies
        run: npm clean-install
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: cache npm dependencies
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: build dependencies
        run: |
          npm ci
      - name: cache coverage report
        uses: actions/cache@v4
        with:
          path: ./coverage/lcov.info
          key: ${{ runner.os }}-coverage-${{ hashFiles('**/lcov.info') }}
          restore-keys: |
            ${{ runner.os }}-coverage-${{ hashFiles('**/lcov.info') }}
            ${{ runner.os }}-coverage-
            ${{ runner.os }}-
      - name: run tests and coverage
        run: |
          npm run coverage

  sonarcloud:
    name: SonarCloud
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: cache coverage report
        uses: actions/cache@v4
        with:
          path: ./coverage/lcov.info
          key: ${{ runner.os }}-coverage-${{ hashFiles('**/lcov.info') }}
          restore-keys: |
            ${{ runner.os }}-coverage-${{ hashFiles('**/lcov.info') }}
            ${{ runner.os }}-coverage-
            ${{ runner.os }}-
      - name: SonarCloud scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
  publish:
    name: publish to github container
    needs: sonarcloud
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: create image name
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}:${{ github.ref_name }}" > $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: publish docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
