name: test-project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository to get access to the code
        uses: actions/checkout@v4
      - name: build dependencies
        run: npm install
      - name: test
        run: npm test
      - name: sonarqube
        run: npm test
