name: test-project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get all directories
        run: |
          ls .
          ls ..
          ls ...

      - name: build dependencies
        run: npm install
      - name: test
        run: npm test
      - name: sonarqube
        run: npm test
